FROM golang:1.15 AS builder
WORKDIR /go/src
COPY . .
RUN go mod download 
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o otaserver .

FROM  alpine:latest
WORKDIR /root/OTAserver
COPY --from=builder  /go/src/otaserver /go/src/config.cfg ./
CMD ["./otaserver"]

